#!/bin/bash
#
##
###  _            _ _                                        
### | |__   __ _ (_|_)_ __ ___   ___    __ _ _ __  _ __  ___ 
### | '_ \ / _` || | | '_ ` _ \ / _ \  / _` | '_ \| '_ \/ __|
### | | | | (_| || | | | | | | |  __/ | (_| | |_) | |_) \__ \
### |_| |_|\__,_|/ |_|_| |_| |_|\___|  \__,_| .__/| .__/|___/6
###            |__/                         |_|   |_|        
###
###  _ _|_ _ ._    _  _  
### (_\/|_(_)|_)\/(_|(/_ 
###   /      |  /  _|                      
###
### hajime_apps
### cytopyge arch linux installation 'applications'
### epilogue of a five part installation series
###
### (c) 2019 cytopyge
###
## 
#

# make rw
sudo mount -o remount,rw  /usr

yay -Syu --noconfirm \

# video tools \
youtube-dl mpv youtube-viewer \

# terminal text tools \
figlet \

# terminal file browser \
nnn ranger vifm \

# file tools \
srm rsync gdisk \

# network tools \
wireshark-cli wireshark-qt mtr \

# download utility \
aria2 \

# internet tools \

## mozilla firefox \
firefox-developer-edition \
[ -d ~/Downloads ] && rm -rf ~/Downloads \
[ -d ~/.mozilla ] && rm -rf ~/.mozilla \
git clone https://gitlab.com/cytopyge/ffxd_init ~/.mozilla \
cd ~/.mozilla \
git checkout -f addons \
cd ~ \

## w3m web browser \
## also for ranger w3m image preview method \
#[TODO] \
w3m \

# system monitoring \
glances ccze \

# virtual machines \
virtualbox virtualbox-host-modules-arch \

# qrcode \
qrencode \

#[TODO] \
# image viewer \
feh imv \

# image editor \
imagemagick \

# pdf viewer \
mupdf zathura-pdf-mupdf \

#[TODO] \
# photo editing \
# yay -S --noconfirm \ 

# libre-office \
# yay -S --noconfirm libreoffice-fresh libreoffice-fresh-nl

# make ro
sudo mount -o remount,ro  /usr

clear
echo 'sh hajime/7logr.sh'
